### ISSUE TITLE
Martinique dock disappears when routes built

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#13]
## Summary

After building one or both of the ferry routes into the Dock of Martinique, the dock disappears and cannot be targeted by a vehicle or the mouse, even when dragging a resource.

## Game Version

Version: LOGistICAL Earth, 852L

## Reproduction Steps

* Have a save where the ferry routes into the Dock of Martinique are not yet built.
* send a boat with boats in its cargo to build the routes
* When the routes are built, observe that the dock is no longer visible.
* restart the game client
* observe that the dock is visible again.

## Expected Behaviour (optional)

Expect dock to remain visible after routes to/from it are built.

**Comment by rayanth** [comment]
This is likely to cause a great deal of confusion for newer players.

**Comment by sacada** [comment]
Fixed 853b
