### ISSUE TITLE
Cadiz, Spain can only be completed by trucks, no road connection

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#19]
## Broken Road or Rail
Cadiz, Spain can only be completed by trucks, but has no connection to the road network. Build 852m
![image](https://user-images.githubusercontent.com/8252741/97370016-4dc11980-186b-11eb-9a2e-a549112f8784.png)

**Comment by rayanth** [comment]
original message - https://discordapp.com/channels/347507296152322050/742172767339937914/770215687901413376

**Comment by rayanth** [comment]
a business affected also, per https://discordapp.com/channels/347507296152322050/742172403093995564/770448682788192297

**Comment by sacada** [comment]
Fixed in #853t
