### ISSUE TITLE
Road near Silver Spring, US remains locked

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#20]
## Broken Road or Rail

A road that is uncompletable (Even when Washington contract is completed) close to Silver Spring

![image](https://user-images.githubusercontent.com/8252741/97370299-e8215d00-186b-11eb-99ec-476bfdf5aebd.png)

**Comment by rayanth** [comment]
https://discordapp.com/channels/347507296152322050/742172403093995564/770295588566204456

**Comment by sacada** [comment]
Fixed 853b
