### ISSUE TITLE
Road near Trebinje not unlocked by contract

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#21]
## Broken Road or Rail

![image](https://user-images.githubusercontent.com/8252741/97370660-bd83d400-186c-11eb-87db-09b4ff3b38c5.png)

**Comment by rayanth** [comment]
https://discordapp.com/channels/347507296152322050/742172403093995564/770296951173939221

**Comment by sacada** [comment]
Fixed 853b.
