### ISSUE TITLE
Rail Access Issues: Talayuela and Navalmoral de la Mata, Spain

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#24]
## Broken Road or Rail

![image](https://user-images.githubusercontent.com/8252741/97371342-36376000-186e-11eb-9674-34ba14878e5b.png)

**Comment by rayanth** [comment]
https://discordapp.com/channels/347507296152322050/742172403093995564/770679163840626699

**Comment by sacada** [comment]
Fixed 853b Disabled road segment.
