### ISSUE TITLE
Broken Rail - New York Area - 852b

### ISSUE THREAD

**Issue by Scarlet-Dragon** [sacada/LOGistICAL#30]
Broken Rail 
v852b 

- Dongan Hills United States
- Flatbush United States
- New Dorp Beach United States

![image](https://user-images.githubusercontent.com/54205922/97578271-7589bc00-19e8-11eb-8b81-1e33503548f5.png)

**Comment by rayanth** [comment]
See #4

**Comment by rayanth** [comment]
closed wrong issue

**Comment by sacada** [comment]
Fixed in #853t
