### ISSUE TITLE
Contract: Turkey Bridge Fix

### ISSUE THREAD

**Issue by Scarlet-Dragon** [sacada/LOGistICAL#33]
The Fatih Sultan Mehmet Köprüsü Asya Geçişi bridge is not showing arrows but is a locked road. 
Also Contract title says Bridge instead of Bridges

![image](https://user-images.githubusercontent.com/54205922/97674011-ac151480-1a84-11eb-8fb6-0164b1316baf.png)

**Comment by sacada** [comment]
Fixed in #853t

"Also Contract title says Bridge instead of Bridges"
I will leave the title as it is the same as all the "road" fixes, as non-plural. The description of the contract does use the plural.
