### ISSUE TITLE
Guangzhou, China - Sea route missing

### ISSUE THREAD

**Issue by Scarlet-Dragon** [sacada/LOGistICAL#34]
Guangzhou, China tagged with sea, but has no sea route

![image](https://user-images.githubusercontent.com/54205922/97679461-31042c00-1a8d-11eb-9fbc-6439dca231f2.png)

**Comment by rayanth** [comment]
confirmed. Port can be completed by rail, but can't send a ship to it.

**Comment by sacada** [comment]
Fixed in #853t
