### ISSUE TITLE
Road Layout: Central Region (Airfield), Ghana

### ISSUE THREAD

**Issue by Scarlet-Dragon** [sacada/LOGistICAL#42]
Truck access to Central Region (Airfield), Ghana takes a bizarre dog-leg towards Takoradi before returning

![image](https://user-images.githubusercontent.com/54205922/97784430-76f8e700-1b96-11eb-8928-1fe616d2de15.png)

![image](https://user-images.githubusercontent.com/54205922/97784441-91cb5b80-1b96-11eb-81c3-f2e73143c327.png)

![image](https://user-images.githubusercontent.com/54205922/97784447-9bed5a00-1b96-11eb-9c27-26d8bc46349e.png)

**Comment by sacada** [comment]
Fixed in #853t
