### ISSUE TITLE
disconnected roads near Brandon, Canada

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#43]
## Broken Road or Rail

Roadworks due south of Brandon, Canada (US/Canada border -- two dimmed roads, not completely connected. Roadworks being pointed at gives message that truck can't reach it, yet nearly every road around is built.

![image](https://user-images.githubusercontent.com/8252741/97786947-22d90d00-1b6c-11eb-9f1e-4344822530df.png)

**Comment by sacada** [comment]
Fixed in #853t
