### ISSUE TITLE
Broken Rail - Naples, Italy

### ISSUE THREAD

**Issue by Scarlet-Dragon** [sacada/LOGistICAL#44]
Large number of towns near Naples, Italy have no railway access (in the image, the towns with yellow and red stripe pin)

![image](https://user-images.githubusercontent.com/54205922/97789157-0eb9fd80-1bb6-11eb-83ac-07d6d7d2fa01.png)

**Comment by Scarlet-Dragon** [comment]
Left ones now fixed. Those on the right still broken.

**Comment by sacada** [comment]
Fixed in #853t
