### ISSUE TITLE
Broken Rail - Italy (Towns)

### ISSUE THREAD

**Issue by Scarlet-Dragon** [sacada/LOGistICAL#46]
Broken Rail in Italy
- Cornate d'Adda 
- Gerenzano 
- Pellaro
- Pizzo
- Selcetta 

![image](https://user-images.githubusercontent.com/54205922/97797480-5fad0e80-1c15-11eb-9947-228c046e1f4f.png)  Cornate d'Adda 
![image](https://user-images.githubusercontent.com/54205922/97798674-08f90200-1c20-11eb-9315-e9bf0ac96f80.png) Gerenzano 
![image](https://user-images.githubusercontent.com/54205922/97821165-57061800-1ca9-11eb-9348-e1660f104809.png) Pellaro
![image](https://user-images.githubusercontent.com/54205922/97804867-715cd900-1c4a-11eb-98fb-8334672fd007.png) Pizzo
![image](https://user-images.githubusercontent.com/54205922/97798886-275ffd00-1c22-11eb-9268-8dc93f05c6e6.png) Selcetta

**Comment by sacada** [comment]
All fixed in #853t
Cornate d'Adda
Gerenzano
Pellaro
Pizzo
Selcetta
