### ISSUE TITLE
Road between Jerusalem and Jordan doesn't connect

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#52]
## Broken Road or Rail
![image](https://user-images.githubusercontent.com/8252741/98296630-10921100-1f68-11eb-9c7c-952cfbe9bfe1.png)

There is a visible road there in satellite imagery

![image](https://user-images.githubusercontent.com/8252741/98296687-1d166980-1f68-11eb-873a-a97a9770eae2.png)

**Comment by sacada** [comment]
If you zoom in closer the road is broken.
![image](https://user-images.githubusercontent.com/22721433/98429606-bde95e00-20fb-11eb-8583-271704ea76c7.png)

**Comment by rayanth** [comment]
well. shucks. OK, then...
