### ISSUE TITLE
Port of Piraeus, Greece

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#69]
## Broken Sea Route

https://images-ext-2.discordapp.net/external/S3kHOQ9guQZ6rWi6QasWVXXPcgI_Y6z8bgdJJ_3TEw4/https/i.imgur.com/JdMEQ4x.png

Port of Piraeus has no Sea Route leading to it...

![image](https://user-images.githubusercontent.com/8252741/99158881-82ffa100-268c-11eb-8b55-9e811b58ac1f.png)

**Comment by sacada** [comment]
Build #854f
