### ISSUE TITLE
Duplicated Rail - Austria / Italy

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#79]
## Broken Road or Rail

Duplicated rail between Pradi, Austria (red pin in image) and Italy. One was buildable when contract was completed. Other shows still locked: 

![image](https://user-images.githubusercontent.com/8252741/99195832-08db2500-273d-11eb-9e41-8820887fc7b1.png)

**Comment by sacada** [comment]
It should now pop with the Italy/Austria Road Fix contract. If you have already done the contract and it doesn't pop, then that is another issue I need to address.
Fixed in build #854f

**Comment by rayanth** [comment]
confirmed, now buildable.
