### ISSUE TITLE
Gennevilliers, France - rail  not connected

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#8]
## Broken Road or Rail

Gennevilliers, France can build a rail station but its segments do not connect to the network... I cannot get a train there.

![image](https://user-images.githubusercontent.com/8252741/97123266-3148a400-16e8-11eb-827a-fcc3ef244114.png)

**Comment by rayanth** [comment]
finally got a chance to check, in 853h. Confirmed, cannot access via rail, though i can build the rail station. Marked up a few "dim" rails in the area : 
![image](https://user-images.githubusercontent.com/8252741/97822629-6a928e00-1c6b-11eb-891a-bfc50cec2546.png)

**Comment by sacada** [comment]
Fixed in #853t
