### ISSUE TITLE
Poland - locked road near Jablunkov

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#82]
## Broken Road or Rail

Road did not unlock from contract completions. It leads only to a single business, Bacówka, which the player heatmap (enabled in image) shows nobody has completed and I have no remaining contracts in this area.

Red pin is on Jablunkov.

![image](https://user-images.githubusercontent.com/8252741/99196884-e698d580-2743-11eb-8066-89c4b2156d9b.png)

**Comment by sacada** [comment]
Remove in build #854f
