### ISSUE TITLE
Road to Nowhere, Canada

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#85]
## Broken Road or Rail

This road segment stems from Tottenham, Canada, but leads nowhere. Tottenham is accessed via south driveway.

![image](https://user-images.githubusercontent.com/8252741/99200137-66309f80-2758-11eb-9779-d7c11d993173.png)

**Comment by sacada** [comment]
That road doesn't exist in the game data. Maybe it is the leftover of an old rail link.

![image](https://user-images.githubusercontent.com/22721433/99218445-98143580-282e-11eb-94cb-4de7f058a4ac.png)
