### ISSUE TITLE
Broken Rail Towns - Russia

### ISSUE THREAD

**Issue by Voxhumbug** [sacada/LOGistICAL#91]
>Yegor'yevsk just outside Moscow
![image](https://user-images.githubusercontent.com/63669877/99620834-53d29200-29f4-11eb-974e-a4e2bdea36f9.png)

>Strugi-Krasnyye near Estonian Border
![image](https://user-images.githubusercontent.com/63669877/99620926-92684c80-29f4-11eb-85db-570ed3d566fb.png)

>Peterhof
![image](https://user-images.githubusercontent.com/63669877/99621046-d8bdab80-29f4-11eb-9aed-c57dd4432b9b.png)

>Near the Crimea:  Novocherkassk, Starocherkasskaya, Shkurinskaya, Kislyakovskaya, and Staronizhestebliyevskaya
![image](https://user-images.githubusercontent.com/63669877/99621391-cc861e00-29f5-11eb-98cd-43a59a8a122d.png)

**Comment by sacada** [comment]
Fixed in build #857n
