### ISSUE TITLE
Broken Rail Towns - Brazil (Southern Network Only) 854i

### ISSUE THREAD

**Issue by Voxhumbug** [sacada/LOGistICAL#92]
>**Sao Paolo area.**  Red/yellow striped pins are broken towns (blue pins are working rail I have pinned as I have not yet built an industry in them)  Americo Brasiliense, Laranjal Paulista, Boituva, Sorocaba, Itanhaem
![image](https://user-images.githubusercontent.com/63669877/99854898-b2fae880-2b53-11eb-8a01-d856f9e74970.png)

>**Rio vicinity** Tocantins, Sapucaia, Niteroi 
![image](https://user-images.githubusercontent.com/63669877/99855086-08cf9080-2b54-11eb-9606-d78ea90ef6f5.png)

>**Recife area**  Natal
![image](https://user-images.githubusercontent.com/63669877/99855195-3f0d1000-2b54-11eb-9aba-45d2d0a3b32f.png)

**Comment by sacada** [comment]
Fixed these and a bunch of others. Not sure if there is more to the last one.
Build #857n
