### ISSUE TITLE
Cyprus - either count is off, or a business is unconnected

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#97]
## Summary

(at the time of writing) Five players have achieved 23 towns and 222 businesses in Cyprus as of 11/26/2020. Cyprus shows 223 businesses on Global Stats. Either count is incorrect, or a business is missing a connection and cannot be discovered.

## Game Version

Version: LOGistICAL Earth, 854t

## Reproduction Steps

* Pick a location in Cyprus
* view Sub-region stats
* note players with 23/222.
* Open Global Stats, Europe, Cyprus
* note totals are 23/223.
* wonder if this is some dirty trick, and you'll never be able to finish the game.

**Comment by sacada** [comment]
There are two copies of Bellapais over the top of each other. I have moved one slightly to allow it to be selected.
Build #855r.
