### ISSUE TITLE
Multi-Nav: Allow Cancelling Route Selection

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#98]
## Summary

Allow the player to cancel the Route Selection Screen (perhaps via Escape)

## Use case

Players who enter Multi-Nav Route Selection on accident and don't want to erase their previously planned route.

## Detailed Description

Particularly in the Vaccine module, but also in Earth, I find myself planning hundred-node routes with Multi-Nav and then sending the truck on its way. Sometimes I will accidentally have that truck selected when I select an industry or storage output, and that forces me back into Route Selection. This poses a problem:
* Previously planned route is not editable
* If you try to add nodes to the previous route, it erases the previous route.
* If you just click 'Done' without selecting any nodes this second time around, the previous route is erased.

So by accidentally entering multi-nav, I've no choice but to erase my previously planned route.

There are occasions where I want to erase the previous route. But usually I do NOT want to. 

I propose:
* Add 'Escape' key bind to cancel Route-Selection in Multi-Nav, without making or saving any of the changes that may have been done while in it (restoring previous route if one existed)
* Additionally, add a "Clear" button below "Done" so the user can Clear an existing route when they actually desire to.

**Comment by sacada** [comment]
Build #855r
